#! /usr/bin/python3

import json
import requests

bands = [
"Wiener Philharmoniker",
"Distorted Harmony",
"Amberian Dawn",
"Evershine",
"Slipknot",
"Susperia",
"We Are the Catalyst",
"Cain's Offering",
"Elvenking",
"Lunatica",
"Lifer",
"Brother Firetribe",
"Nemesea",
"Red Hot Chili Peppers",
"Factory Of Dreams",
"Secret Illusion",
"Thirty Seconds To Mars",
"Anubis Gate",
"Balance Of Power",
"Ripper Owens",
"Sinner",
"Dark Moor",
"The 69 Eyes",
"Polarization",
"Mendel",
"Arion",
"Märvel",
"Lancer",
"Nocturnal Rites",
"The Claymore",
"The Sins Of Thy Beloved",
"Atargatis",
"I Legion",
"Starset",
"Striker",
"Power Quest",
"Winterborn",
"Avenged Sevenfold",
"Sinbreed",
"Noctura",
"Sara",
"Twilight Force",
"Cans",
"Wilderun",
"Find Me",
"Turisas",
"Lordi",
"Stephan Forté",
"The Birthday Massacre",
"Atma Weapon",
"Maegi",
"Nautiluz",
"AFI",
"Domina Noctis",
"Revolution Renaissance",
"Voices Of Destiny",
"Avantasia",
"Vagus Nerve",
"Emilie Autumn",
"Conquering Dystopia",
"Killrbuckeye",
"Tiluland",
"Ascension",
"Stratovarius",
"Masterplan",
"Adrenaline Mob",
"Macbeth",
"Symphonic Destiny",
"Arjen Anthony Lucassen's Star One",
"Santa Cruz",
"Edge Of Attack",
"Dream Evil",
"Jeff Loomis",
"Ville Valo",
"Crashdiet",
"Solisia",
"Ramin Djawadi",
"Tengger Cavalry",
"Xandria",
"Hollow Haze",
"Vanden Plas",
"Biffy Clyro",
"Poisonblack",
"Noveria",
"Dawn Of Silence",
"Elvellon",
"PelleK",
"One Desire",
"Dark Princess",
"Rhapsody",
"Primal Fear",
"Meytal",
"Chronus",
"Jelonek",
"Pyramaze",
"Trivium",
"Warmen",
"Katatonia",
"Royal Hunt",
"Black Majesty",
"Tristania",
"Charon",
"Rhapsody Of Fire",
"Between The Buried And Me",
"Angel Of Eden",
"Amaranthe",
"Derdian",
"Nightwish",
"Tomorrow's Outlook",
"Amorphis",
"Palace",
"Heimdall",
"Heavy Metal Ninjas",
"So Hideous",
"Angtoria",
"Sad Alice Said",
"Almanac",
"Aurelio Voltaire",
"U.D.O.",
"Dream Theater",
"Nightingale",
"Leverage",
"Damnation Angels",
"Eternal Idol",
"Chris Mike",
"Diabulus in Musica",
"Sunrise",
"Luca Turilli",
"Axxis",
"Northern Kings",
"Darkseed",
"Andy James",
"Shadow Hunters",
"DragonForce",
"Sara",
"Ludwig van Beethoven",
"Kissin' Dynamite",
"Iron Fire",
"Imperia",
"Against Myself",
"Pomegranate Tiger",
"Theatre Of Tragedy",
"Steve Vai",
"Pathfinder",
"Gonzalo Sanhueza",
"Mogwai",
"Anette Olzon",
"Divine Ascension",
"Dionysus",
"Enbound",
"Edguy",
"GALNERYUS",
"Unisonic",
"The Dirty Youth",
"Elias Viljanen",
"Beautiful Sin",
"Iced Earth",
"Sister Sin",
"Magnum",
"After All",
"Entwine",
"Naio Ssaion",
"Korn",
"Stream of Passion",
"Borealis",
"Sôber",
"Veonity",
"Ancient Bards",
"James Labrie",
"Symphonity",
"Serenity",
"John Williams",
"Burning Point",
"Darksun",
"Within Temptation",
"Anthriel",
"Eternal Tears Of Sorrow",
"Orden Ogan",
"Shakra",
"Eyefear",
"Hysterica",
"Thaurorod",
"Heavy Tiger",
"Metalium",
"Almah",
"Domine",
"Sammy Berell",
"Asrai",
"Widek",
"Wintergatan",
"Blood Stain Child",
"Angel Vivaldi",
"ReVamp",
"Apocalyptica",
"Lacrimas Profundere",
"Symphony X",
"Lacuna Coil",
"Pretty Maids",
"Liv Kristine",
"Evergrey",
"Deathstars",
"We Are The Fallen",
"Andy James",
"X JAPAN",
"Opera Magna",
"Soulspell",
"Dragony",
"Conquer Divide",
"Dreamstate",
"At Vance",
"Iron Mask",
"Solence",
"Black Light Discipline",
"Edenbridge",
"Leprous",
"Angel Dust",
"Gordon Hempton",
"Helloween",
"Silent Force",
"Tuomas Holopainen",
"A Life Divided",
"Silentium",
"Blowsight",
"Saidian",
"Devin Townsend Project",
"Freedom Call",
"Communic",
"In Flames",
"Winter In Eden",
"Sirenia",
"Epica",
"Stormwarrior",
"Symfonia",
"Tarja",
"Tears Of Magdalena",
"Sturm und Drang",
"Leah",
"Vision Divine",
"Apocalypse Orchestra",
"Lords of Black",
"DGM",
"Diztord",
"Altaria",
"Lullacry",
"Sonata Arctica",
"Therion",
"Marty Friedman",
"Pythia",
"System Of A Down",
"Lost Horizon",
"Emerald Sun",
"Kobra And The Lotus",
"SpellBlast",
"Visions of Atlantis",
"Evanescence",
"Kiana",
"Arven",
"Dragonland",
"Deadlock",
"Anberlin",
"Valkyre",
"Red Rose",
"Cayne",
"Ebony Ark",
"Timeless Miracle",
"West-Eastern Divan Orchestra",
"Jet",
"Winterstorm",
"Theocracy",
"BABYMETAL",
"Dark Lunacy",
"Leaves' Eyes",
"Circles",
"Destiny Potato",
"Dawn of Destiny",
"Iron Savior",
"Zonata",
"Elysion",
"Defueld",
"After Forever",
"Trillium",
"Gus G.",
"Phantasma",
"Secret Sphere",
"Kilpi",
"Heavatar",
"Timo Tolkki’s Avalon",
"Art Nation",
"Celesty",
"Linkin Park",
"Angeldark",
"Katra",
"Machinae Supremacy",
"Cryonic Temple",
"Unsun",
"The Animal In Me",
"The Duskfall",
"Enkelination",
"Grave Digger",
"Bloodbound",
"To/Die/For",
"Delain",
"Bathory",
"For My Pain...",
"Crimson Sun",
"Days Of Jupiter",
"Eisbrecher",
"Battlelore",
"Michael Angelo Batio",
"Firewind",
"Excalion",
"Withem",
"Hibria",
"Operatika",
"Helker",
"HIM",
"Trail Of Tears",
"Thessa",
"Axenstar",
"Crystallion",
"Ignea",
"My Chemical Romance",
"Angra",
"Nordic Union",
"Beyond Twilight",
"H.E.A.T",
"Ari Koivunen",
"Gloryhammer",
"ERock",
"Kamelot",
"Bonfire",
"Bullet For My Valentine",
"Igor Stravinsky",
"Heavenly",
"Blind Guardian",
"Agonizer",
"Fairyland",
"Praying Mantis",
"Civilization One",
"Crystal Ball",
"Supralightning",
"Majesty Of Revival",
"Ron Wasserman",
"Orphaned Land"
]

api_key="b5ff9dcd-5c94-450d-9b75-d0ae39fba23c"
url ='http://em.wemakesites.net/albums/upcoming?api_key=%s' % (api_key)

response = requests.get(url)
response.raise_for_status()
upcoming = json.loads(response.text)
U = upcoming['data']['upcoming_albums']

for album in U:
	if album['band']['name'] in bands:
		print(album['album']['title'], album['band']['name'], album['release_date'])
